version: '3.3'

services:
  discord-bot:
    build: ./discord-bot
    links: 
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
        - mongodata:/data/db 
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD} 
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
        - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
        - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
        - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
volumes:
  mongodata:
    external: true
